name: Mainframe CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  update-mainframe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Zowe CLI
        run: |
          npm install -g @zowe/cli
          zowe plugins install @zowe/cli
      
      - name: Configure Zowe Profile
        run: |
          zowe profiles create zosmf-profile github-profile --host 204.90.115.200 --port 10443 --user Z21335 --password GDQ76ZQP --reject-unauthorized false
      
      - name: Update Member in Mainframe
        run: |
          echo "Updated content" > file1.txt
          zowe zos-files upload file-to-data-set "update.txt" "Z21335.TEST.PDS(file1)"
